{% set version = "0.8"%}

package:
  name: dac_test
  version: {{ version }}

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - openblas
  run:
    - openblas

#test:
#  imports:
#    ?

about:
  home: http://ambermd.org
  #license: LGPL or GPL?
  #license_family: LGPL or GPL?
  #license_file:
  summary: Molecular simulation tools for ../../amber_phenix-0.8

extra:
  recipe-maintainers:
    - bkpoon
